FROM python:3.6

LABEL maintainer="antoine.charbel@inmind.ai"

COPY docker/requirements.txt .
ENV HOME /root

COPY src/main /main

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
	locales \
        wget \
        software-properties-common \
        ca-certificates \
        build-essential \
        cmake \
        git \
        libopencv-dev \
        python3-dev \
        python3-pip \
        libgtk2.0-dev\
        pkg-config\
    && apt-get -y autoremove \
    && apt-get clean \
    && pip3 install setuptools wheel \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN pip install -r requirements.txt


WORKDIR ${HOME}
RUN git clone http://github.com/opencv/opencv.git && cd opencv \
    && git checkout master                   \
    && mkdir build && cd build              \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE    \
        -D CMAKE_INSTALL_PREFIX=/usr/local  \
        -D WITH_CUDA=OFF                     \
        -D WITH_OPENCL=OFF                  \
        -D ENABLE_FAST_MATH=1               \
        -D CUDA_FAST_MATH=1                 \
        -D WITH_CUBLAS=1                    \
        -D BUILD_DOCS=OFF                   \
        -D BUILD_PERF_TESTS=OFF             \
        -D BUILD_TESTS=OFF                  \
        ..                                  \
    && make -j `nproc`                      \
    && make install                         \
    && cd ${HOME} && rm -rf ./opencv/


WORKDIR /main
CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "7770"]
